### PR TITLE
remove intent based enqueue options

### PR DESCRIPTION
**Pull request by jozefKruszynski**

### CODE REVIEW

**Review by marcelveldt — APPROVED** [review]

**Comment by marcelveldt** [comment]
tests are failing ?

**Comment by OzGav** [comment]
Out of interest what is this fixing?

**Comment by marcelveldt** [comment]
> Out of interest what is this fixing?

It will just use the defaults that are now configurable in the settings

**Comment by OzGav** [comment]
Ok I am looking at those settings now I think. Should some of them have [default][default] after them? Seems a duplication for some reason?

**Pull request merged**
